import { theme } from 'antd';
import type { ThemeConfig } from 'antd';

const { darkAlgorithm } = theme;

export const antdThemeConfig: ThemeConfig = {
  algorithm: darkAlgorithm,
  token: {
    colorPrimary: '#00E5CC',
    colorInfo: '#00E5CC',
    colorSuccess: '#00E5CC',
    colorWarning: '#FAAD14',
    colorError: '#FF4D4F',
    colorBgBase: '#0A0A0A',
    colorBgContainer: '#1A1A2E',
    colorBgElevated: '#2A2A3E',
    colorBgLayout: '#0A0A0A',
    colorBgSpotlight: '#2A2A3E',
    colorBorder: '#2A2A3E',
    colorBorderSecondary: '#2A2A3E',
    colorText: '#FFFFFF',
    colorTextSecondary: 'rgba(255, 255, 255, 0.65)',
    colorTextTertiary: 'rgba(255, 255, 255, 0.45)',
    colorTextQuaternary: 'rgba(255, 255, 255, 0.25)',
    colorFill: 'rgba(255, 255, 255, 0.18)',
    colorFillSecondary: 'rgba(255, 255, 255, 0.12)',
    colorFillTertiary: 'rgba(255, 255, 255, 0.08)',
    colorFillQuaternary: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 4,
    borderRadiusLG: 4,
    borderRadiusSM: 4,
    borderRadiusXS: 2,
    controlHeight: 32,
    controlHeightLG: 40,
    controlHeightSM: 24,
    controlHeightXS: 20,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"',
    fontFamilyCode: 'JetBrains Mono, Fira Code, monospace',
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeSM: 12,
    lineHeight: 1.5,
  },
  components: {
    Button: {
      colorPrimary: '#00E5CC',
      colorPrimaryHover: '#00B3A0',
      colorPrimaryActive: '#00998A',
      borderRadius: 4,
      controlHeight: 32,
      controlHeightLG: 40,
      controlHeightSM: 24,
      primaryColor: '#0A0A0A',
    },
    Slider: {
      colorPrimary: '#00E5CC',
      colorPrimaryHover: '#00B3A0',
      handleColor: '#00E5CC',
      handleSize: 14,
      handleSizeHover: 16,
      railBg: '#2A2A3E',
      railSize: 4,
      trackBg: '#00E5CC',
    },
    Input: {
      colorBgContainer: '#2A2A3E',
      colorBorder: '#2A2A3E',
      colorPrimaryHover: '#00E5CC',
      borderRadius: 4,
      controlHeight: 32,
      controlHeightLG: 40,
      controlHeightSM: 24,
      activeBg: '#2A2A3E',
      hoverBorderColor: '#00E5CC',
      activeBorderColor: '#00E5CC',
      activeShadow: '0 0 0 2px rgba(0, 229, 204, 0.1)',
    },
    InputNumber: {
      colorBgContainer: '#2A2A3E',
      colorBorder: '#2A2A3E',
      colorPrimaryHover: '#00E5CC',
      borderRadius: 4,
      controlHeight: 32,
      hoverBorderColor: '#00E5CC',
      activeBorderColor: '#00E5CC',
      activeShadow: '0 0 0 2px rgba(0, 229, 204, 0.1)',
    },
    Select: {
      colorBgContainer: '#2A2A3E',
      colorBorder: '#2A2A3E',
      colorPrimaryHover: '#00E5CC',
      borderRadius: 4,
      controlHeight: 32,
      controlHeightLG: 40,
      controlHeightSM: 24,
      optionSelectedBg: 'rgba(0, 229, 204, 0.1)',
      hoverBorderColor: '#00E5CC',
      activeBorderColor: '#00E5CC',
    },
    Card: {
      colorBgContainer: '#1A1A2E',
      colorBorderSecondary: '#2A2A3E',
      borderRadius: 4,
      borderRadiusLG: 4,
    },
    Modal: {
      colorBgElevated: '#1A1A2E',
      borderRadiusLG: 8,
    },
    Drawer: {
      colorBgElevated: '#1A1A2E',
    },
    Menu: {
      colorBgContainer: '#1A1A2E',
      colorItemText: 'rgba(255, 255, 255, 0.65)',
      colorItemTextHover: '#00E5CC',
      colorItemTextSelected: '#00E5CC',
      colorItemBgSelected: 'rgba(0, 229, 204, 0.1)',
      colorSubItemBg: 'transparent',
      borderRadius: 4,
      itemBorderRadius: 4,
    },
    Tabs: {
      colorPrimary: '#00E5CC',
      colorText: '#FFFFFF',
      colorTextSecondary: 'rgba(255, 255, 255, 0.65)',
      inkBarColor: '#00E5CC',
      itemColor: 'rgba(255, 255, 255, 0.65)',
      itemHoverColor: '#00E5CC',
      itemSelectedColor: '#00E5CC',
    },
    Progress: {
      colorPrimary: '#00E5CC',
    },
    Checkbox: {
      colorPrimary: '#00E5CC',
      colorPrimaryHover: '#00B3A0',
    },
    Radio: {
      colorPrimary: '#00E5CC',
      colorPrimaryHover: '#00B3A0',
    },
    Switch: {
      colorPrimary: '#00E5CC',
    },
    Tag: {
      colorBgContainer: 'rgba(0, 229, 204, 0.1)',
      colorBorder: 'rgba(0, 229, 204, 0.3)',
      colorText: '#00E5CC',
      borderRadiusSM: 4,
    },
    Tooltip: {
      colorBgSpotlight: '#1A1A2E',
      borderRadius: 4,
    },
    Popover: {
      colorBgElevated: '#1A1A2E',
      borderRadiusLG: 8,
    },
    Dropdown: {
      colorBgElevated: '#1A1A2E',
      borderRadiusLG: 8,
    },
    DatePicker: {
      colorBgContainer: '#2A2A3E',
      colorBorder: '#2A2A3E',
      colorPrimaryHover: '#00E5CC',
      borderRadius: 4,
      activeBg: '#2A2A3E',
      hoverBorderColor: '#00E5CC',
      activeBorderColor: '#00E5CC',
      activeShadow: '0 0 0 2px rgba(0, 229, 204, 0.1)',
    },
    Message: {
      colorBgElevated: '#1A1A2E',
    },
    Notification: {
      colorBgElevated: '#1A1A2E',
    },
  },
};

export default antdThemeConfig;
